language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  matrix:
    - TOX_ENV=py35-dj20
    - TOX_ENV=py35-dj21
    - TOX_ENV=py35-dj22
    - TOX_ENV=py36-dj20
    - TOX_ENV=py36-dj21
    - TOX_ENV=py36-dj22
    - TOX_ENV=py37-dj20
    - TOX_ENV=py37-dj21
    - TOX_ENV=py37-dj22

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
