language: python

python:
  - "3.7"

env:
  matrix:
    - TOXENV="py35-dj20"
    - TOXENV="py35-dj21"
    - TOXENV="py35-dj22"
    - TOXENV="py36-dj20"
    - TOXENV="py36-dj21"
    - TOXENV="py36-dj22"
    - TOXENV="py37-dj20"
    - TOXENV="py37-dj21"
    - TOXENV="py37-dj22"

install:
  - pip install tox

script:
  - tox

after_success:
  - coveralls
